// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whvojpkgfqylscfefocz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indodm9qcGtnZnF5bHNjZmVmb2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTg3NDMsImV4cCI6MjA3NDAzNDc0M30.mQyeoGxkX2QEQxTM-ApRn6xQvazdLssZjhDi2jhGg-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});